<# 
  Copyright (c) 2026 Stephen Hsu (chiacheng.hsu@owasp.org). All rights reserved.
  This software is 100% owned and licensed by Stephen Hsu.
  Unauthorized copying or distribution is strictly prohibited.

  setup.ps1 — One-Click WebRTC Streamer Setup for Windows
  Usage: Set-ExecutionPolicy Bypass -Scope Process -Force; ./setup.ps1
#>

param(
    [switch]$Rebuild,
    [switch]$Stop
)

$ErrorActionPreference = "Stop"

# ── ANSI Colors ───────────────────────────────────────
function Write-Step  ($msg) { Write-Host "  [*] $msg" -ForegroundColor Cyan }
function Write-OK    ($msg) { Write-Host "  [✓] $msg" -ForegroundColor Green }
function Write-Err   ($msg) { Write-Host "  [✗] $msg" -ForegroundColor Red }
function Write-Info  ($msg) { Write-Host "  [i] $msg" -ForegroundColor Yellow }

# ── Banner ────────────────────────────────────────────
Write-Host ""
Write-Host "  ╔══════════════════════════════════════════╗" -ForegroundColor Magenta
Write-Host "  ║   WebRTC Streamer — LAN Setup Script     ║" -ForegroundColor Magenta
Write-Host "  ║   © 2026 Stephen Hsu (OWASP)             ║" -ForegroundColor Magenta
Write-Host "  ╚══════════════════════════════════════════╝" -ForegroundColor Magenta
Write-Host ""

# ── Handle --Stop flag ────────────────────────────────
if ($Stop) {
    Write-Step "Stopping containers..."
    docker compose down
    Write-OK "All containers stopped."
    exit 0
}

# ── Step 1: Check Docker ─────────────────────────────
Write-Step "Checking Docker..."
try {
    $dockerVersion = docker version --format '{{.Server.Version}}' 2>&1
    if ($LASTEXITCODE -ne 0) { throw "Docker not responding" }
    Write-OK "Docker Engine $dockerVersion detected."
} catch {
    Write-Err "Docker is not running or not installed."
    Write-Info "Please install Docker Desktop: https://www.docker.com/products/docker-desktop"
    exit 1
}

# Check docker compose
try {
    docker compose version | Out-Null
    Write-OK "Docker Compose available."
} catch {
    Write-Err "Docker Compose plugin not found."
    Write-Info "Update Docker Desktop to get the Compose plugin."
    exit 1
}

# ── Step 2: Detect LAN IP ─────────────────────────────
Write-Step "Detecting LAN IP address..."

$lanIP = $null

# Method 1: Get the IP of the adapter with a default gateway
$adapters = Get-NetIPConfiguration | Where-Object {
    $_.IPv4DefaultGateway -ne $null -and
    $_.NetAdapter.Status -eq "Up"
}

if ($adapters) {
    $lanIP = ($adapters | Select-Object -First 1).IPv4Address.IPAddress
}

# Method 2: Fallback — parse ipconfig
if (-not $lanIP) {
    $ipconfig = ipconfig | Select-String "IPv4 Address" | Select-Object -First 1
    if ($ipconfig -match "(\d+\.\d+\.\d+\.\d+)") {
        $lanIP = $Matches[1]
    }
}

if (-not $lanIP) {
    Write-Err "Could not detect LAN IP."
    $lanIP = Read-Host "  Please enter your LAN IP manually"
}

Write-OK "LAN IP: $lanIP"

# ── Step 3: Generate .env ─────────────────────────────
Write-Step "Generating .env file..."

$envContent = @"
# Auto-generated by setup.ps1 — $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
# Copyright (c) 2026 Stephen Hsu (chiacheng.hsu@owasp.org). All rights reserved.

LAN_IP=$lanIP
ALLOWED_ORIGINS=https://${lanIP}:443,https://${lanIP},http://${lanIP}:80,http://${lanIP}
"@

$envContent | Out-File -FilePath ".env" -Encoding utf8 -Force
Write-OK ".env created with LAN_IP=$lanIP"

# ── Step 4: Build Docker Images ──────────────────────
Write-Step "Building Docker images (this may take a few minutes)..."

$buildArgs = @("compose", "build")
if ($Rebuild) {
    $buildArgs += "--no-cache"
    Write-Info "Rebuild mode: --no-cache enabled"
}

& docker @buildArgs
if ($LASTEXITCODE -ne 0) {
    Write-Err "Docker build failed. Check the output above."
    exit 1
}
Write-OK "Images built successfully."

# ── Step 5: Start Containers ─────────────────────────
Write-Step "Starting containers..."
docker compose up -d
if ($LASTEXITCODE -ne 0) {
    Write-Err "Failed to start containers."
    exit 1
}
Write-OK "Containers are running."

# ── Step 6: Wait for Caddy ───────────────────────────
Write-Step "Waiting for Caddy to initialize TLS..."
Start-Sleep -Seconds 5

# ── Final Output ─────────────────────────────────────
Write-Host ""
Write-Host "  ╔══════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "  ║          SETUP COMPLETE                  ║" -ForegroundColor Green
Write-Host "  ╚══════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""
Write-Host "  HTTPS (recommended):" -ForegroundColor White
Write-Host "  ────────────────────────────────────────" -ForegroundColor DarkGray
Write-Host "  Home:      " -NoNewline; Write-Host "https://${lanIP}" -ForegroundColor Cyan
Write-Host "  Sender:    " -NoNewline; Write-Host "https://${lanIP}/sender" -ForegroundColor Yellow
Write-Host "  Receiver:  " -NoNewline; Write-Host "https://${lanIP}/receiver" -ForegroundColor Magenta
Write-Host "  CA Cert:   " -NoNewline; Write-Host "https://${lanIP}/cert" -ForegroundColor DarkYellow
Write-Host ""
Write-Host "  HTTP (fallback — camera may not work on all browsers):" -ForegroundColor White
Write-Host "  ────────────────────────────────────────" -ForegroundColor DarkGray
Write-Host "  Sender:    " -NoNewline; Write-Host "http://${lanIP}/sender" -ForegroundColor Yellow
Write-Host "  Receiver:  " -NoNewline; Write-Host "http://${lanIP}/receiver" -ForegroundColor Magenta
Write-Host "  ────────────────────────────────────────" -ForegroundColor DarkGray
Write-Host ""
Write-Host "  QUICK START:" -ForegroundColor White
Write-Host "  1. On phone: open https://${lanIP}/sender (accept cert warning)" -ForegroundColor DarkGray
Write-Host "  2. If camera blocked: install CA cert from https://${lanIP}/cert" -ForegroundColor DarkGray
Write-Host "  3. In OBS: add Browser Source -> https://${lanIP}/receiver" -ForegroundColor DarkGray
Write-Host ""
Write-Host "  CERT INSTALL (eliminates browser warnings):" -ForegroundColor DarkYellow
Write-Host "    iOS:     Open https://${lanIP}/cert in Safari -> Install Profile" -ForegroundColor DarkGray
Write-Host "    Android: Open https://${lanIP}/cert -> Settings > Security > Install" -ForegroundColor DarkGray
Write-Host "    Manual:  docker cp webrtc-caddy:/data/caddy/pki/authorities/local/root.crt ." -ForegroundColor DarkGray
Write-Host ""
Write-Host "  Commands:" -ForegroundColor White
Write-Host "    ./setup.ps1 -Stop         Stop all containers" -ForegroundColor DarkGray
Write-Host "    ./setup.ps1 -Rebuild      Rebuild without cache" -ForegroundColor DarkGray
Write-Host "    docker compose logs -f     View live logs" -ForegroundColor DarkGray
Write-Host ""
